### ISSUE TITLE
Flatpak version of app: MainMenu popups misplaced

### ISSUE THREAD

**Issue by Alexey-T** [flathub/io.github.cudatext.CudaText-Qt5#41] opened 2023-12-17 11:53 UTC
https://synwrite.sourceforge.net/forums/viewtopic.php?t=3081

**Comment by JordanL2** [comment] 2023-12-17 12:02
The flatpak has been using `fixes_3_0` branch since two weeks ago, so it should contain the fix that solves that issue... I'll try to reproduce by setting up a local Gnome session.

**Comment by JordanL2** [comment] 2024-01-05 20:22
I updated to tag `lazarus_3_0` which definitely contains the commits that were supposed to fix [the issue](https://gitlab.com/freepascal.org/lazarus/lazarus/-/issues/40602):

https://gitlab.com/freepascal.org/lazarus/lazarus/-/commit/fc9064853556ac2080f887c6b357aa1cc28c24ad
https://gitlab.com/freepascal.org/lazarus/lazarus/-/commit/1416ae9a4dcf810fa290292774919f0db6e222e3
https://gitlab.com/freepascal.org/lazarus/lazarus/-/commit/ad8e69f7c947379dc36f4a0e02bc2af0853ea892

There is still an issue in Gnome+Wayland (I've not tested Xorg). When I click on a menu item (eg "Edit") it is positioned correctly, but if I then hover the mouse over another menu item without closing the menu, the next menu is positioned at the top-left corner of the screen. Other than that, menus work fine. This might be a separate bug from the one they closed with the original fix.

**Comment by Alexey-T** [comment] 2024-01-05 20:27
I submitted your feedback to the Gitlab issue.

**Comment by JordanL2** [comment] 2024-02-04 11:03
Now CudaText is being built with Lazarus 3.0 this bug is not reproducible for me.

**Closed by JordanL2** 2024-02-04 11:03 UTC
